import BreadCrumb from "../BreadCrumbs/BreadCrumb";
import TreeStructure from "../Explore/ExploreTopics/Tree/TreeStructure";
import CodeBlock from "../ui/CodeBlock";

type breadCrumbType = {
  breadCrumb: string;
};

type GuideStep = {
  title: string;
  description: string;
  fileName: string;
  code: string;
  language?: string;
};

const zustandSteps: GuideStep[] = [
  {
    title: "Install Zustand (one tiny dependency)",
    description:
      "Zustand is just a hook creator, so there is no provider/setup ceremony. Install it and start writing stores.",
    fileName: "terminal",
    language: "bash",
    code: ["npm install zustand"].join("\n"),
  },
  {
    title: "Create a store hook",
    description:
      "A store is a function generated by create(). You define the state shape and the actions in one place.",
    fileName: "src/store/useBearStore.ts",
    language: "ts",
    code: [
      'import { create } from "zustand";',
      "",
      "type BearState = {",
      "  bears: number;",
      "  addBear: () => void;",
      "  reset: () => void;",
      "};",
      "",
      "export const useBearStore = create<BearState>((set) => ({",
      "  bears: 0,",
      "  addBear: () => set((state) => ({ bears: state.bears + 1 })),",
      "  reset: () => set({ bears: 0 }),",
      "}));",
    ].join("\n"),
  },
  {
    title: "Consume the store inside a component",
    description:
      "Call the hook anywhere. Only the selected state re-renders which keeps components extremely fast.",
    fileName: "src/components/BearCounter.tsx",
    language: "tsx",
    code: [
      'import { useBearStore } from "../store/useBearStore";',
      "",
      "const BearCounter = () => {",
      "  const { bears, addBear, reset } = useBearStore();",
      "",
      "  return (",
      '    <div className="rounded-2xl border border-emerald-200 bg-white p-4 shadow-sm">',
      '      <p className="text-lg font-semibold">Bears: {bears}</p>',
      '      <div className="mt-3 flex gap-2">',
      '        <button className="btn" onClick={addBear}>Add</button>',
      '        <button className="btn btn-ghost" onClick={reset}>Reset</button>',
      "      </div>",
      "    </div>",
      "  );",
      "};",
      "",
      "export default BearCounter;",
    ].join("\n"),
  },
  {
    title: "Add middleware (devtools, persist, selectors)",
    description:
      "Wrap create() calls with middleware helpers to unlock debugging, localStorage persistence, and granular selectors.",
    fileName: "src/store/useBearStore.ts",
    language: "ts",
    code: [
      'import { create } from "zustand";',
      'import { devtools, persist } from "zustand/middleware";',
      "",
      "type BearState = {",
      "  bears: number;",
      "  addBear: () => void;",
      "};",
      "",
      "export const useBearStore = create<BearState>()(",
      "  devtools(",
      "    persist(",
      "      (set) => ({",
      "        bears: 0,",
      "        addBear: () => set((state) => ({ bears: state.bears + 1 })),",
      "      }),",
      '      { name: "bear-storage" }',
      "    )",
      "  )",
      ");",
      "",
      "export const selectBears = (state: BearState) => state.bears;",
    ].join("\n"),
  },
];

const Zustand: React.FC<breadCrumbType> = ({ breadCrumb }) => {
  return (
    <div className="flex h-full w-full flex-col gap-4 overflow-auto px-2 py-2 sm:px-0">
      <BreadCrumb breadCrumb={breadCrumb} />
      <p className="text-sm text-slate-600">
        Zustand keeps global state ergonomic by exposing a store as a simple
        hook. No providers, minimal boilerplate, and full TypeScript support.
      </p>

      <div
        className="w-full overflow-x-auto"
        aria-label="Suggested folder structure"
      >
        <TreeStructure
          rootFolder="src"
          files={[
            "store/useBearStore.ts",
            "components/BearCounter.tsx",
            "App.tsx",
          ]}
        />
      </div>

      <div className="flex flex-col gap-4">
        {zustandSteps.map((step, index) => (
          <section
            key={step.title}
            className="rounded-2xl border border-emerald-200 bg-white p-3 shadow-sm sm:p-4"
          >
            <div className="mb-3 flex flex-col gap-1">
              <span className="text-xs font-semibold uppercase tracking-wide text-emerald-500">
                Step {index + 1}
              </span>
              <h3 className="text-lg font-semibold text-slate-900">
                {step.title}
              </h3>
              <p className="text-sm text-slate-600">{step.description}</p>
            </div>
            <CodeBlock
              code={step.code}
              fileName={step.fileName}
              language={step.language}
            />
          </section>
        ))}
      </div>
    </div>
  );
};

export default Zustand;
